#! /bin/csh -f
setenv SOLPSTOP $HOME/solps-iter # sbb
if (-s b2mn.exe.dir/b2ftrace) then
  set FILE=b2mn.exe.dir/b2ftrace
else
  set FILE=b2ftrace
endif
if (-X zcat) then
  set ZCAT="zcat --force"
else
  set ZCAT="gzip --decompress --force --stdout"
endif
if($?GNUPLOT_TMP) then
  set tmpdir="$GNUPLOT_TMP/"
else
  set tmpdir=""
endif

setenv PLOT_FROM_FILE "gnuplot.temp"
$ZCAT $FILE | \
  awk 'BEGIN{ig=0}/data/&&ig==0{ig=1}/data/&&ig==2{printf "\n"}/^[^*]/&&ig>0{ig=2;printf "%s",$0}' | \
  $SOLPSTOP/scripts/resopt $argv | \
  awk '{print $2,$3,$4,$5,$6,$7,$8,$9,$10}' #>! ${tmpdir}PLOT_FROM_FILE
#plot xlyplot8 `count -p conD 0 1` `count -p momD 0 1` totmom ee ei phi iteration 'norm of residuals' $PWD
